/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author João Amorim
 */

import java.util.concurrent.Semaphore;

public class SystemGUI extends javax.swing.JFrame {

    /**
     * Creates new form SystemGUI
     */
    private Mechanism m;    
    public  Semaphore sem_getpart = new Semaphore(0);
    public  Semaphore sem_distribution = new Semaphore(0);
    
    public int dock1 = -1;
    public int dock2 = -1;
    private int type1count=0;
    private int type2count=0;
    private int type3count=0;
    private int dock1count=0;
    private int dock2count=0;
    private int dockEndcount=0;

    public SystemGUI(Mechanism mechanism) {
        initComponents();
        this.m = mechanism;
    }
   
    public void writeInGUI(String s){
        jTextArea1.append(s+"\n");
    }
    
    public void updatePackageCount(int type){
        switch(type){
            case 1:
                type1count++;
                text_type1total.setText(Integer.toString(type1count)); 
                break;
            case 2:
                type2count++; 
                text_type2total.setText(Integer.toString(type2count));
                break;
            case 3:
                type3count++;
                text_type3total.setText(Integer.toString(type3count));
                break;
            default:
                break;
        }
    }
    
    public void updateDockCount(int dock, int type){
        switch(dock){
            case 1:
                dock1count++;
                text_dock1total.setText(Integer.toString(dock1count));
                switch (type) {
                    case 1:
                        int t1 = Integer.parseInt(text_dock1type1.getText());
                        t1++;
                        text_dock1type1.setText(Integer.toString(t1));
                        break;
                    case 2:
                        int t2 = Integer.parseInt(text_dock1type2.getText());
                        t2++;
                        text_dock1type2.setText(Integer.toString(t2));
                        break;
                    default:
                        int t3 = Integer.parseInt(text_dock1type3.getText());
                        t3++;
                        text_dock1type3.setText(Integer.toString(t3));
                        break;
                }
                break;
            case 2:
                dock2count++;
                text_dock2total.setText(Integer.toString(dock2count));
                switch (type) {
                    case 1:
                        int t1 = Integer.parseInt(text_dock2type1.getText());
                        t1++;
                        text_dock2type1.setText(Integer.toString(t1));
                        break;
                    case 2:
                        int t2 = Integer.parseInt(text_dock2type2.getText());
                        t2++;
                        text_dock2type2.setText(Integer.toString(t2));
                        break;
                    default:
                        int t3 = Integer.parseInt(text_dock2type3.getText());
                        t3++;
                        text_dock2type3.setText(Integer.toString(t3));
                        break;
                }
                break;
            case 3:
                dockEndcount++;
                text_dockEndtotal.setText(Integer.toString(dockEndcount));
                switch (type) {
                    case 1:
                        int t1 = Integer.parseInt(text_dockEndType1.getText());
                        t1++;
                        text_dockEndType1.setText(Integer.toString(t1));
                        break;
                    case 2:
                        int t2 = Integer.parseInt(text_dockEndType2.getText());
                        t2++;
                        text_dockEndType2.setText(Integer.toString(t2));
                        break;
                    default:
                        int t3 = Integer.parseInt(text_dockEndType3.getText());
                        t3++;
                        text_dockEndType3.setText(Integer.toString(t3));
                        break;
                }
                break;
            default: break;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_package = new javax.swing.JButton();
        button_conveyor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        text_dock1boxtype = new java.awt.TextField();
        text_dock2boxtype = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        button_dockconfig = new javax.swing.JButton();
        button_emergency = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        text_type1total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        text_type2total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        text_type3total = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text_dock1total = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        text_dock2total = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        text_dockEndtotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        text_dock1type1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        text_dock1type2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        text_dock1type3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        text_dock2type2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        text_dock2type3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        text_dock2type1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        text_dockEndType2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        text_dockEndType3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        text_dockEndType1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_package.setText("SEND PACKAGE");
        button_package.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_packageActionPerformed(evt);
            }
        });

        button_conveyor.setBackground(new java.awt.Color(102, 255, 102));
        button_conveyor.setText("START CONVEYOR");
        button_conveyor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_conveyorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Sistemas em Tempo Real");

        jLabel2.setText("LABWORK 2 - SPLITTER CONVEYOR");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("System statistics and information:");

        text_dock1boxtype.setText("");
        text_dock1boxtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_dock1boxtypeActionPerformed(evt);
            }
        });
        text_dock1boxtype.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                text_dock1boxtypeTextValueChanged(evt);
            }
        });

        text_dock2boxtype.setText("");
        text_dock2boxtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_dock2boxtypeActionPerformed(evt);
            }
        });
        text_dock2boxtype.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                text_dock2boxtypeTextValueChanged(evt);
            }
        });

        jLabel4.setText("Dock 1 Box Type");

        jLabel5.setText("Dock 2 Box Type");

        button_dockconfig.setText("ENABLE DOCK CONFIGURATION");
        button_dockconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dockconfigActionPerformed(evt);
            }
        });

        button_emergency.setBackground(new java.awt.Color(255, 51, 51));
        button_emergency.setText("EMERGENCY STOP");
        button_emergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_emergencyActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel7.setText("Total of type 1 packages delivered:");

        text_type1total.setText("0");

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel8.setText("Total of type 2 packages delivered:");

        text_type2total.setText("0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel9.setText("Total of type 3 packages delivered:");

        text_type3total.setText("0");
        text_type3total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_type3totalActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel10.setText("Total of packages delivered at dock 1:");

        text_dock1total.setText("0");

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel11.setText("Total of packages delivered at dock 2:");

        text_dock2total.setText("0");

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel12.setText("Total of packages delivered at dock E:");

        text_dockEndtotal.setText("0");

        jLabel13.setText("Type 1:");

        text_dock1type1.setText("0");

        jLabel14.setText("Type 2:");

        text_dock1type2.setText("0");

        jLabel15.setText("Type 3:");

        text_dock1type3.setText("0");

        jLabel16.setText("Type 2:");

        text_dock2type2.setText("0");

        jLabel17.setText("Type 3:");

        text_dock2type3.setText("0");

        jLabel18.setText("Type 1:");

        text_dock2type1.setText("0");

        jLabel19.setText("Type 2:");

        text_dockEndType2.setText("0");

        jLabel20.setText("Type 3:");

        text_dockEndType3.setText("0");

        jLabel21.setText("Type 1:");

        text_dockEndType1.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel6.setText("Sistemas em Tempo Real - Turno P5 - António Pegado, João Amorim, Rafael Castellano");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel22.setText("Ano letivo 2021/2022");

        jButton1.setText("Clear screen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(button_dockconfig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(button_package, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(button_conveyor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(button_emergency, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text_type2total, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text_type1total, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text_type3total, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text_dock1boxtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text_dock2boxtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_dock1total, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_dock1type1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_dock1type2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_dock1type3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(text_dockEndtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text_dockEndType1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text_dockEndType2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text_dockEndType3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(text_dock2total, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text_dock2type1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text_dock2type2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text_dock2type3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_dock1boxtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_dock2boxtype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_conveyor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_package, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_dockconfig, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_emergency, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(text_type1total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(text_type2total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(text_type3total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(text_dock1total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(text_dock1type1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(text_dock1type2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(text_dock1type3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(text_dock2total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(text_dock2type1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(text_dock2type2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(text_dock2type3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(text_dockEndType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(text_dockEndType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(text_dockEndType3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(text_dockEndtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel22))
                .addContainerGap())
        );

        button_emergency.setEnabled(false);
        text_type1total.setEditable(false);
        text_type2total.setEditable(false);
        text_type3total.setEditable(false);
        text_dock1total.setEditable(false);
        text_dock2total.setEditable(false);
        text_dockEndtotal.setEditable(false);
        text_dock1type1.setEditable(false);
        text_dock1type2.setEditable(false);
        text_dock1type3.setEditable(false);
        text_dock2type2.setEditable(false);
        text_dock2type3.setEditable(false);
        text_dock2type1.setEditable(false);
        text_dockEndType2.setEditable(false);
        text_dockEndType3.setEditable(false);
        text_dockEndType1.setEditable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_packageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_packageActionPerformed
        if(m.start && !m.blocked_state && !m.interrupted){
            jTextArea1.append("Sending package...\n");
            ThreadGetPart.startGetPart();
        } else jTextArea1.append("Operation currently unavailable...\n");
             
    }//GEN-LAST:event_button_packageActionPerformed

    private void button_conveyorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_conveyorActionPerformed
        
        if(dock1==-1 && dock2==-1)
            jTextArea1.append("Conveyor won't start without dock configuration...\n");
        else{
            button_emergency.setEnabled(true);
            if(!m.start){
                m.start=true;
                m.moveConveyor();
                jTextArea1.append("Conveyor started!\n");
                button_conveyor.setBackground(new java.awt.Color(255, 99, 71));
                button_conveyor.setText("STOP CONVEYOR");
            }
            else{
                m.start=false;
                m.stopConveyor();
                jTextArea1.append("Conveyor stopped!\n");
                button_conveyor.setBackground(new java.awt.Color(102, 255, 102));
                button_conveyor.setText("START CONVEYOR");
            }
        }
    }//GEN-LAST:event_button_conveyorActionPerformed

    private void text_dock1boxtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_dock1boxtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_dock1boxtypeActionPerformed

    private void text_dock1boxtypeTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_text_dock1boxtypeTextValueChanged
        // TODO add your handling code here:
        dock1 = Integer.parseInt(text_dock1boxtype.getText());
        text_dock1boxtype.setEditable(false);
    }//GEN-LAST:event_text_dock1boxtypeTextValueChanged

    private void text_dock2boxtypeTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_text_dock2boxtypeTextValueChanged
        dock2 = Integer.parseInt(text_dock2boxtype.getText());
        text_dock2boxtype.setEditable(false);
// TODO add your handling code here:
    }//GEN-LAST:event_text_dock2boxtypeTextValueChanged

    private void button_dockconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dockconfigActionPerformed
       jTextArea1.append("Dock configuration enable(top right corner)\n");
       text_dock1boxtype.setEditable(true);
       text_dock2boxtype.setEditable(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_button_dockconfigActionPerformed

    private void button_emergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_emergencyActionPerformed
        if(button_emergency.isSelected()){
            jTextArea1.append("SUSPENDING ALL TASKS!\n");
            button_conveyor.setEnabled(false);
            button_package.setEnabled(false);
            button_dockconfig.setEnabled(false);
            
            ThreadStopResume.Stop(); m.stop_state=true;
            
            button_emergency.setText("RESUME OPERATIONS");
        }
        else{
            jTextArea1.append("RESUMING TASKS!\n");
            button_conveyor.setEnabled(true);
            button_package.setEnabled(true);
            button_dockconfig.setEnabled(true);
            
           ThreadStopResume.Resume(); m.stop_state=false;
            
            button_emergency.setText("EMERGENCY STOP");
        }
            
// TODO add your handling code here:
    }//GEN-LAST:event_button_emergencyActionPerformed

    private void text_type3totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_type3totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_type3totalActionPerformed

    private void text_dock2boxtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_dock2boxtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_dock2boxtypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    jTextArea1.setText("");
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SystemGUI(m).setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_conveyor;
    private javax.swing.JButton button_dockconfig;
    private javax.swing.JToggleButton button_emergency;
    private javax.swing.JButton button_package;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.TextField text_dock1boxtype;
    private javax.swing.JTextField text_dock1total;
    private javax.swing.JTextField text_dock1type1;
    private javax.swing.JTextField text_dock1type2;
    private javax.swing.JTextField text_dock1type3;
    private java.awt.TextField text_dock2boxtype;
    private javax.swing.JTextField text_dock2total;
    private javax.swing.JTextField text_dock2type1;
    private javax.swing.JTextField text_dock2type2;
    private javax.swing.JTextField text_dock2type3;
    private javax.swing.JTextField text_dockEndType1;
    private javax.swing.JTextField text_dockEndType2;
    private javax.swing.JTextField text_dockEndType3;
    private javax.swing.JTextField text_dockEndtotal;
    private javax.swing.JTextField text_type1total;
    private javax.swing.JTextField text_type2total;
    private javax.swing.JTextField text_type3total;
    // End of variables declaration//GEN-END:variables

}

